### ISSUE TITLE
I want to add C++ Program for finding age - Age Calculator

### ISSUE THREAD

**Issue by minhaj-313** [TecHAyusH6476/DSA-Prep-HacktoberFest22#13]
C++ Program to finding age -
Please assign me under hacktoberfest.
In which folder i creat this program please tell me.
Thank You

**Comment by TecHAyusH6476** [comment]
@minhaj-313 I will create others named folder upload your code in it.
Happy Hacktober !!!

**Comment by minhaj-313** [comment]
> @minhaj-313 I will create others named folder upload your code in it. Happy Hacktober !!!

Thank You.

**Comment by TecHAyusH6476** [comment]
I have created the folder

**Comment by minhaj-313** [comment]
> I have created the folder

done, I will Sending you a PR. Merge it by labeling hacktoberfest-accepted.
Thank you so much.

**Comment by TecHAyusH6476** [comment]
Yeah done ! Thanks for contributing

**Comment by minhaj-313** [comment]
> Yeah done ! Thanks for contributing

PLEASE Label my PR as hacktoberfest-accepted.
Thank You
