### ISSUE TITLE
I want to add Tree programs in your repo. Can you assign me pllease?

### ISSUE THREAD

**Issue by tussharpaul13** [TecHAyusH6476/DSA-Prep-HacktoberFest22#29]
Programs like: Find node at k distance , calculate size of tree, inorder,preorder,postorder traversal,Maximum depth/height of tree !!

**Comment by TecHAyusH6476** [comment]
@tussharpaul13 Yeah sure you can add tree programs but please make sure to have them inside same topic (tree) folder.
Happy Hacktober !!!

**Comment by TecHAyusH6476** [comment]
Also please verify the programs before generating the PRs

**Comment by tussharpaul13** [comment]
> Also please verify the programs before generating the PRs

ok sir

**Comment by TecHAyusH6476** [comment]
Closed
